<a href="https://colab.research.google.com/github/VineetSivadasan/houses/blob/main/Use_case_KNN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [11]:
  import numpy as np
  import pandas as pd
  import matplotlib.pyplot as plt
  import matplotlib.image as mpimg
  
  from scipy.stats import multivariate_normal as mvn
  
  %matplotlib inline
  df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/MNIST_train.csv')
  df.head()

   Unnamed: 0  index  labels  0  1  2  3  ...  777  778  779  780  781  782  783
0           0      0       5  0  0  0  0  ...    0    0    0    0    0    0    0
1           1      1       0  0  0  0  0  ...    0    0    0    0    0    0    0
2           2      2       4  0  0  0  0  ...    0    0    0    0    0    0    0
3           3      3       1  0  0  0  0  ...    0    0    0    0    0    0    0
4           4      4       9  0  0  0  0  ...    0    0    0    0    0    0    0

[5 rows x 787 columns]

In [12]:
df.shape

(60000, 787)

In [13]:
df_array = df.to_numpy() #turn the training dataset into an array
df_array

array([[    0,     0,     5, ...,     0,     0,     0],
       [    1,     1,     0, ...,     0,     0,     0],
       [    2,     2,     4, ...,     0,     0,     0],
       ...,
       [59997, 59997,     5, ...,     0,     0,     0],
       [59998, 59998,     6, ...,     0,     0,     0],
       [59999, 59999,     8, ...,     0,     0,     0]])

In [14]:
print_NaN_rows = df[df.isnull().any(axis=1)] #list the rows where NaN appears
print_NaN_rows

Empty DataFrame
Columns: [Unnamed: 0, index, labels, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, ...]
Index: []

[0 rows x 787 columns]

In [15]:
print_None_rows = df[df.eq("None").any(axis=1)]  #check to see if there are any 'None' values in any row
print_NaN_rows.shape

(0, 787)

In [16]:
y = df_array[:,2] #extract the label column
y

array([5, 0, 4, ..., 5, 6, 8])

In [17]:
y.shape

(60000,)

In [18]:
X = np.delete(df_array, [0,1,2], axis=1)

In [29]:
X_normalised = X/255

In [30]:
#using KNN method
class KNNClassifier():
  def fit(self,X,y):
    self.X=X
    self.y=y

  def predict(self, X, K, epsilon=1e-3):
    N=len(X)
    y_hat_KNN =  np.zeros(N)

    for i in range (N):
      dist2=np.sum((self.X-X[i])**2, axis=1)
      idxt = np.argsort(dist2)[:K]
      gamma_k = 1/(np.sqrt(dist2[idxt])+epsilon)
      y_hat_KNN[i] =np.bincount(self.y[idxt], weights=gamma_k).argmax()
    
    return y_hat_KNN

In [32]:
knn=KNNClassifier()
knn.fit(X_normalised,y)

In [36]:
y_hat_KNN = knn.predict(X_normalised,20)

In [38]:
df_test = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/MNIST_test.csv')
df_test.head()

   Unnamed: 0  index  labels  0  1  2  3  ...  777  778  779  780  781  782  783
0           0      0       7  0  0  0  0  ...    0    0    0    0    0    0    0
1           1      1       2  0  0  0  0  ...    0    0    0    0    0    0    0
2           2      2       1  0  0  0  0  ...    0    0    0    0    0    0    0
3           3      3       0  0  0  0  0  ...    0    0    0    0    0    0    0
4           4      4       4  0  0  0  0  ...    0    0    0    0    0    0    0

[5 rows x 787 columns]

In [39]:
df_test_array = df_test.to_numpy()
df_test_array

array([[   0,    0,    7, ...,    0,    0,    0],
       [   1,    1,    2, ...,    0,    0,    0],
       [   2,    2,    1, ...,    0,    0,    0],
       ...,
       [9997, 9997,    4, ...,    0,    0,    0],
       [9998, 9998,    5, ...,    0,    0,    0],
       [9999, 9999,    6, ...,    0,    0,    0]])

In [40]:
y_test = df_test_array[:,2] #extract the label column
y_test

array([7, 2, 1, ..., 4, 5, 6])

In [41]:
X_test = np.delete(df_test_array, [0,1,2], axis=1)

In [42]:
X_test_normalised = X_test/255   #double slash to produce integer values instead of float

In [43]:
y_hat_KNN = knn.predict(X_test_normalised,20)

In [37]:
def accuracy(y,y_hat_KNN):
  return np.mean(y== y_hat_KNN)


accuracy(y,y_hat_KNN)

1.0

In [ ]:
prescription = mpimg.imread('/content/drive/MyDrive/Colab Notebooks/prescription.jpg')
prescription

array([[[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       ...,

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]]], dtype=uint8)

In [ ]:
prescription.shape

(774, 800, 3)